# Generated by Django 6.0.7 on 2026-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/", verbose_name="Файл")),
                (
                    "name_file",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                (
                    "size_file",
                    models.BigIntegerField(verbose_name="Размер файла в байтах"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Тип файла"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание файла"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичность"),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество скачиваний"
                    ),
                ),
                (
                    "share_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Ссылка для общего доступа",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
