# Generated by Django 6.0.7 on 2026-08-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="size_file",
            field=models.BigIntegerField(
                default=0, verbose_name="Размер файла в байтах"
            ),
        ),
    ]
