# Generated by Django 6.0.7 on 2026-08-15 03:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_file_size_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("user", "name_file", "size_file")},
        ),
    ]
